version: "3"
services:
  ngrok-bob:
    image: wernight/ngrok
    command: ngrok http bob-agent:${BOB_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  bob-agent:
    build: .
    environment:
      NGROK_NAME: ngrok-bob
      AGENT_NAME: Bob
      PORT: ${BOB_HTTP_PORT}
      ADMIN_PORT: ${BOB_ADMIN_PORT}
    ports:
      - ${BOB_HTTP_PORT}:${BOB_HTTP_PORT}
      - ${BOB_ADMIN_PORT}:${BOB_ADMIN_PORT}
    networks:
      - indy_demo

  ngrok-alice:
    image: wernight/ngrok
    command: ngrok http alice-agent:${ALICE_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  alice-agent:
    build: .
    environment:
      NGROK_NAME: ngrok-alice
      AGENT_NAME: Alice
      PORT: ${ALICE_HTTP_PORT}
      ADMIN_PORT: ${ALICE_ADMIN_PORT}
    ports:
      - ${ALICE_HTTP_PORT}:${ALICE_HTTP_PORT}
      - ${ALICE_ADMIN_PORT}:${ALICE_ADMIN_PORT}
    networks:
      - indy_demo
  alice-notebook:
    build:
      context: ../../libs/aries-basic-controller
      args:
        - jupyter_port=${ALICE_JUPYTER_PORT}
    depends_on:
      - alice-agent
    networks:
      - indy_demo
    volumes:
      - ./demo/alice:/workspace
    ports:
      - "8888:8888"
      - ${ALICE_WEBHOOK_PORT}:${ALICE_WEBHOOK_PORT}
  bob-notebook:
    build:
      context: ../../libs/aries-basic-controller
      args:
        - jupyter_port=${BOB_JUPYTER_PORT}
    depends_on:
      - bob-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/demo/bob:/workspace
    ports:
      - "8889:8888"
      - ${BOB_WEBHOOK_PORT}:${BOB_WEBHOOK_PORT}

networks:
  indy_demo:
