version: "3"
services:
  ngrok-id-verifier:
    image: wernight/ngrok
    command: ngrok http id-verifier-agent:${IDVERIFIER_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  id-verifier-agent:
    build: ""
    environment:
      NGROK_NAME: ngrok-id-verifier
      AGENT_NAME: Identity Verification Sevice
      PORT: ${IDVERIFIER_HTTP_PORT}
      ADMIN_PORT: ${IDVERIFIER_ADMIN_PORT}
      WEBHOOK_URL: ${IDVERIFIER_WEBHOOK_URL}
    ports:
      - ${IDVERIFIER_HTTP_PORT}:${IDVERIFIER_HTTP_PORT}
      - ${IDVERIFIER_ADMIN_PORT}:${IDVERIFIER_ADMIN_PORT}
    networks:
      - indy_demo

  ngrok-med-school:
    image: wernight/ngrok
    command: ngrok http medical-school-agent:${MEDICAL_SCHOOL_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  medical-school-agent:
    build: ""
    environment:
      NGROK_NAME: ngrok-med-school
      AGENT_NAME: Medical School
      PORT: ${MEDICAL_SCHOOL_HTTP_PORT}
      ADMIN_PORT: ${MEDICAL_SCHOOL_ADMIN_PORT}
      WEBHOOK_URL: ${MEDICAL_SCHOOL_WEBHOOK_URL}
    ports:
      - ${MEDICAL_SCHOOL_HTTP_PORT}:${MEDICAL_SCHOOL_HTTP_PORT}
      - ${MEDICAL_SCHOOL_ADMIN_PORT}:${MEDICAL_SCHOOL_ADMIN_PORT}
    networks:
      - indy_demo
  med-school-notebook:
    build:
      context: ../../
      dockerfile: tutorials/dockerfiles/Dockerfile.basiccontroller
      args:
        - jupyter_port=${MEDICAL_SCHOOL_JUPYTER_PORT}
    depends_on:
      - medical-school-agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks/medical-school:/workspace
    ports:
      - "8888:8888"
      - ${MEDICAL_SCHOOL_WEBHOOK_PORT}:${MEDICAL_SCHOOL_WEBHOOK_PORT}
  id-verifier-notebook:
    build:
      context: ../../
      dockerfile: tutorials/dockerfiles/Dockerfile.basiccontroller
      args:
        - jupyter_port=${IDVERIFIER_JUPYTER_PORT}
    depends_on:
      - id-verifier-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/notebooks/id-verifier:/workspace
    ports:
      - "8889:8888"
      - ${IDVERIFIER_WEBHOOK_PORT}:${IDVERIFIER_WEBHOOK_PORT}
  ngrok-gmc:
    image: wernight/ngrok
    command: ngrok http gmc-agent:${GMC_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  gmc-agent:
    build: ""
    environment:
      NGROK_NAME: ngrok-gmc
      AGENT_NAME: Medical School
      PORT: ${GMC_HTTP_PORT}
      ADMIN_PORT: ${GMC_ADMIN_PORT}
      WEBHOOK_URL: ${GMC_WEBHOOK_URL}
    ports:
      - ${GMC_HTTP_PORT}:${GMC_HTTP_PORT}
      - ${GMC_ADMIN_PORT}:${GMC_ADMIN_PORT}
    networks:
      - indy_demo
  gmc-notebook:
    build:
      context: ../../
      dockerfile: tutorials/dockerfiles/Dockerfile.basiccontroller
      args:
        - jupyter_port=${GMC_JUPYTER_PORT}
    depends_on:
      - gmc-agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks/gmc:/workspace
    ports:
      - "8890:8888"
      - ${GMC_WEBHOOK_PORT}:${GMC_WEBHOOK_PORT}
  ngrok-hee:
    image: wernight/ngrok
    command: ngrok http hee-agent:${HEE_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  hee-agent:
    build: ""
    environment:
      NGROK_NAME: ngrok-gmc
      AGENT_NAME: Medical School
      PORT: ${HEE_HTTP_PORT}
      ADMIN_PORT: ${HEE_ADMIN_PORT}
      WEBHOOK_URL: ${HEE_WEBHOOK_URL}
    ports:
      - ${HEE_HTTP_PORT}:${HEE_HTTP_PORT}
      - ${HEE_ADMIN_PORT}:${HEE_ADMIN_PORT}
    networks:
      - indy_demo
  hee-notebook:
    build:
      context: ../../
      dockerfile: tutorials/dockerfiles/Dockerfile.basiccontroller
      args:
        - jupyter_port=${HEE_JUPYTER_PORT}
    depends_on:
      - hee-agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks/hee:/workspace
    ports:
      - "8891:8888"
      - ${HEE_WEBHOOK_PORT}:${HEE_WEBHOOK_PORT}
networks:
  indy_demo:
