version: "3"
services:
  red-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    ports:
      - ${RED_HTTP_PORT}:${RED_HTTP_PORT}
      - ${RED_ADMIN_PORT}:${RED_ADMIN_PORT}
    depends_on:
      - ledger-nodes
    networks:
      - indy_demo
    entrypoint: /bin/bash
    command: [
        "-c",
          "echo Waiting for ledger to be ready...;
          sleep 60;
          curl -d '{\"seed\":\"${RED_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${RED_AGENT_NAME}\"}' -X POST ${LEDGER_URL}/register; \
          sleep 2; \
            aca-py start \
          --inbound-transport http '0.0.0.0' ${RED_HTTP_PORT} \
          --outbound-transport http \
          --endpoint ${RED_AGENT_ENDPOINT} \
          --webhook-url ${RED_WEBHOOK_URL} \
          --wallet-type 'indy' \
          --seed '${RED_WALLET_SEED}' \
          --admin '0.0.0.0' ${RED_ADMIN_PORT} \
          --admin-insecure-mode \
          --log-level info \
          --genesis-url '${LEDGER_URL}/genesis'
          --label ${RED_AGENT_NAME}",
        ]
  blue-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    ports:
      - ${BLUE_HTTP_PORT}:${BLUE_HTTP_PORT}
      - ${BLUE_ADMIN_PORT}:${BLUE_ADMIN_PORT}
    depends_on:
      - ledger-nodes
    networks:
      - indy_demo
#    volumes:
#      - blue-wallet:/indy/home/.indy_client/default
    entrypoint: /bin/bash
    command: [
        "-c",
        "echo Waiting for ledger to be ready...;
        sleep 60;
        curl -d '{\"seed\":\"${BLUE_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${BLUE_AGENT_NAME}\"}' -X POST ${LEDGER_URL}/register; \
        sleep 2; \
        aca-py start \
        --inbound-transport http '0.0.0.0' ${BLUE_HTTP_PORT} \
        --outbound-transport http \
        --endpoint ${BLUE_AGENT_ENDPOINT} \
        --webhook-url ${BLUE_WEBHOOK_URL} \
        --wallet-type 'indy' \
        --seed '${BLUE_WALLET_SEED}' \
        --admin '0.0.0.0' ${BLUE_ADMIN_PORT} \
        --admin-insecure-mode \
        --log-level info \
        --genesis-url '${LEDGER_URL}/genesis'
        --label ${BLUE_AGENT_NAME}",
    ]
  yellow-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    ports:
      - ${YELLOW_HTTP_PORT}:${YELLOW_HTTP_PORT}
      - ${YELLOW_ADMIN_PORT}:${YELLOW_ADMIN_PORT}
    depends_on:
      - ledger-nodes
    networks:
      - indy_demo
    entrypoint: /bin/bash
    command: [
        "-c",
          "echo Waiting for ledger to be ready...;
          sleep 60;
          curl -d '{\"seed\":\"${YELLOW_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${YELLOW_AGENT_NAME}\"}' -X POST ${LEDGER_URL}/register; \
          sleep 2; \
            aca-py start \
          --inbound-transport http '0.0.0.0' ${YELLOW_HTTP_PORT} \
          --outbound-transport http \
          --endpoint ${YELLOW_AGENT_ENDPOINT} \
          --webhook-url ${YELLOW_WEBHOOK_URL} \
          --wallet-type 'indy' \
          --seed '${YELLOW_WALLET_SEED}' \
          --admin '0.0.0.0' ${YELLOW_ADMIN_PORT} \
          --admin-insecure-mode \
          --log-level info \
          --genesis-url '${LEDGER_URL}/genesis'
          --label ${YELLOW_AGENT_NAME}",
    ]
  alice-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    ports:
      - ${ALICE_HTTP_PORT}:${ALICE_HTTP_PORT}
      - ${ALICE_ADMIN_PORT}:${ALICE_ADMIN_PORT}
    depends_on:
      - ledger-nodes
    networks:
      - indy_demo
    entrypoint: /bin/bash
    command: [
        "-c",
          "echo Waiting for ledger to be ready...;
          sleep 60;
          curl -d '{\"seed\":\"${ALICE_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${ALICE_AGENT_NAME}\"}' -X POST ${LEDGER_URL}/register; \
          sleep 2; \
            aca-py start \
          --inbound-transport http '0.0.0.0' ${ALICE_HTTP_PORT} \
          --outbound-transport http \
          --endpoint ${ALICE_AGENT_ENDPOINT} \
          --webhook-url ${ALICE_WEBHOOK_URL} \
          --wallet-type 'indy' \
          --seed '${ALICE_WALLET_SEED}' \
          --admin '0.0.0.0' ${ALICE_ADMIN_PORT} \
          --admin-insecure-mode \
          --log-level info \
          --genesis-url '${LEDGER_URL}/genesis'
          --label ${ALICE_AGENT_NAME}",
    ]
  setup:
    build:
      context: ../../libs/aries-basic-controller
      dockerfile: Dockerfile.setup
    networks:
      - indy_demo
    depends_on:
      - blue-agent
      - red-agent
      - yellow-agent
#    ports:
#      - ${BLUE_WEBHOOK_PORT}:${BLUE_WEBHOOK_PORT}
#      - ${RED_WEBHOOK_PORT}:${RED_WEBHOOK_PORT}
    environment:
      - BLUE_ADMIN_URL=http://blue-agent:${BLUE_ADMIN_PORT}
      - BLUE_WEBHOOK_PORT=${BLUE_WEBHOOK_PORT}
      - BLUE_WEBHOOK_HOST=0.0.0.0
      - RED_ADMIN_URL=http://red-agent:${RED_ADMIN_PORT}
      - RED_WEBHOOK_PORT=${RED_WEBHOOK_PORT}
      - RED_WEBHOOK_HOST=0.0.0.0
      - YELLOW_ADMIN_URL=http://yellow-agent:${YELLOW_ADMIN_PORT}
      - YELLOW_WEBHOOK_PORT=${YELLOW_WEBHOOK_PORT}
      - YELLOW_WEBHOOK_HOST=0.0.0.0
    entrypoint: /bin/bash
    command:
      [
        "-c",
        "sleep 80;
        python ./create_connection.py"
      ]
  blue-notebook:
    build:
      context: ../../libs/aries-basic-controller
      args:
        - jupyter_port=${BLUE_JUPYTER_PORT}
    depends_on:
      - blue-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/demo/vote_counter:/workspace
    ports:
      - "8888:8888"
      - ${BLUE_WEBHOOK_PORT}:${BLUE_WEBHOOK_PORT}
  red-notebook:
    build:
      context: ../../libs/aries-basic-controller
      args:
        - jupyter_port=${RED_JUPYTER_PORT}
    depends_on:
      - red-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/demo/vote_counter:/workspace
    ports:
      - "8889:8888"
      - ${RED_WEBHOOK_PORT}:${RED_WEBHOOK_PORT}
  yellow-notebook:
    build:
      context: ../../libs/aries-basic-controller
      args:
        - jupyter_port=${YELLOW_JUPYTER_PORT}
    depends_on:
      - yellow-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/demo/vote_counter:/workspace
    ports:
      - "8900:8888"
      - ${YELLOW_WEBHOOK_PORT}:${YELLOW_WEBHOOK_PORT}
  alice-notebook:
    build:
      context: ../../libs/aries-basic-controller
      args:
        - jupyter_port=${ALICE_JUPYTER_PORT}
    depends_on:
      - alice-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/demo/voter:/workspace
    ports:
      - "8901:8888"
      - ${ALICE_WEBHOOK_PORT}:${ALICE_WEBHOOK_PORT}
  ledger-browser:
    build:
      context: https://github.com/bcgov/von-network.git
      dockerfile: Dockerfile
    command: "bash -c 'sleep 10; ./scripts/start_webserver.sh;'"
    environment:
      - DOCKERHOST=${DOCKERHOST}
      - MAX_FETCH=50000
      - RESYNC_TIME=120
      - REGISTER_NEW_DIDS=True
      - LEDGER_INSTANCE_NAME=localhost
    ports:
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    volumes:
      - webserver-cli:/home/indy/.indy-cli
      - webserver-ledger:/home/indy/ledger
    networks:
      - indy_demo

  ledger-nodes:
    build:
      context: https://github.com/bcgov/von-network.git
      dockerfile: Dockerfile
    command: "bash -c './scripts/start_nodes.sh'"
    ports:
      - 9701:9701
      - 9702:9702
      - 9703:9703
      - 9704:9704
      - 9705:9705
      - 9706:9706
      - 9707:9707
      - 9708:9708
    environment:
      - DOCKERHOST=${DOCKERHOST}
    volumes:
      - nodes-data:/home/indy/ledger
    networks:
      - indy_demo

networks:
  indy_demo:
volumes:
  webserver-cli:
  webserver-ledger:
  nodes-data:
