version: "3"
services:
  alice-agent:
    image: alice-protocol:agent
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.attachmentprotocol
    environment:
      - ADMIN_URL=http://alice-agent:${ALICE_ADMIN_PORT}
      - AGENT_NAME=${ALICE_AGENT_NAME}
      - ADMIN_PORT=${ALICE_ADMIN_PORT}
      - HTTP_PORT=${ALICE_HTTP_PORT}
      - WEBHOOK_URL=${ALICE_WEBHOOK_URL}
      - AGENT_ENDPOINT=${ALICE_AGENT_ENDPOINT}
      - WALLET_SEED=${ALICE_WALLET_SEED}
      - WALLET_NAME=${ALICE_WALLET_NAME}
      - WALLET_TYPE=${WALLET_TYPE}
      - WALLET_KEY=${ALICE_WALLET_KEY}
      - ACAPY_ADMIN_API_KEY=${ALICE_API_KEY}
      - GENESIS_URL=${GENESIS_URL}
      - ACAPY_NO_LEDGER=true
    ports:
      - ${ALICE_HTTP_PORT}:${ALICE_HTTP_PORT}
      - ${ALICE_ADMIN_PORT}:${ALICE_ADMIN_PORT}
    networks:
      - indy_demo
    entrypoint: /bin/bash
    command: [
        "-c",
        "
          sleep 5; \
          python3 scripts/parse_yml_env_variables.py -c ./configuration/aries-args-basic.yaml; \
          aca-py start --arg-file /tmp/agent_conf.yml"
      ]
  bob-agent:
    image: bob-protocol:agent
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.attachmentprotocol
    environment:
      - ADMIN_URL=http://bob-agent:${BOB_ADMIN_PORT}
      - AGENT_NAME=${BOB_AGENT_NAME}
      - ADMIN_PORT=${BOB_ADMIN_PORT}
      - HTTP_PORT=${BOB_HTTP_PORT}
      - WEBHOOK_URL=${BOB_WEBHOOK_URL}
      - AGENT_ENDPOINT=${BOB_AGENT_ENDPOINT}
      - WALLET_SEED=${BOB_WALLET_SEED}
      - WALLET_NAME=${BOB_WALLET_NAME}
      - WALLET_TYPE=${WALLET_TYPE}
      - WALLET_KEY=${BOB_WALLET_KEY}
      - ACAPY_ADMIN_INSECURE_MODE=${BOB_ADMIN_SECURE}
      - GENESIS_URL=${GENESIS_URL}
      - ACAPY_NO_LEDGER=true
      - ACAPY_PLUGIN=attach_protocol.attachment_protocol
    ports:
      - ${BOB_HTTP_PORT}:${BOB_HTTP_PORT}
      - ${BOB_ADMIN_PORT}:${BOB_ADMIN_PORT}
    networks:
      - indy_demo
    entrypoint: /bin/bash
    command: [
        "-c",
        "
          sleep 5; \
          python3 scripts/parse_yml_env_variables.py -c ./configuration/aries-args-basic.yaml; \
          aca-py start --arg-file /tmp/agent_conf.yml"
    ]
  setup:
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.createconnection
    networks:
      - indy_demo
    depends_on:
      - alice-agent
      - bob-agent
#    ports:
#      - ${ALICE_WEBHOOK_PORT}:${ALICE_WEBHOOK_PORT}
#      - ${BOB_WEBHOOK_PORT}:${BOB_WEBHOOK_PORT}
    environment:
      - ALICE_ADMIN_URL=http://alice-agent:${ALICE_ADMIN_PORT}
      - ALICE_WEBHOOK_PORT=${ALICE_WEBHOOK_PORT}
      - ALICE_API_KEY=${ALICE_API_KEY}
      - ALICE_WEBHOOK_HOST=0.0.0.0
      - BOB_ADMIN_URL=http://bob-agent:${BOB_ADMIN_PORT}
      - BOB_WEBHOOK_PORT=${BOB_WEBHOOK_PORT}
      - BOB_WEBHOOK_HOST=0.0.0.0
    entrypoint: /bin/bash
    command:
      [
        "-c",
        "sleep 5;
        python ./create_connection.py"
      ]
  alice-notebook:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.attachmentcontroller
      args:
        - jupyter_port=${ALICE_JUPYTER_PORT}
    depends_on:
      - alice-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/notebooks/alice:/workspace
    ports:
      - "8888:8888"
      - ${ALICE_WEBHOOK_PORT}:${ALICE_WEBHOOK_PORT}
  bob-notebook:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.attachmentcontroller
      args:
        - jupyter_port=${BOB_JUPYTER_PORT}
    depends_on:
      - bob-agent
    networks:
      - indy_demo
    volumes:
      - ${PWD}/notebooks/bob:/workspace
    ports:
      - "8889:8888"
      - ${BOB_WEBHOOK_PORT}:${BOB_WEBHOOK_PORT}

networks:
  indy_demo:
